# Generated by Django 5.1.7 on 2025-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('foto', models.ImageField(upload_to='focos_fotos/')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
