# Generated by Django 5.1.7 on 2025-03-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foco',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foco',
            name='foto',
            field=models.ImageField(blank=True, upload_to='focos_fotos/'),
        ),
    ]
